SELECT id,
       email,
       "firstName",
       "lastName",
       password,
       "authProvider",
       role,
       "isEmailVerified",
       "verificationToken",
       "resetPasswordToken",
       "resetPasswordExpires",
       "phoneNumber",
       address,
       city,
       state,
       "zipCode",
       country,
       "lastLogin",
       "createdAt",
       "updatedAt"
FROM public.users
LIMIT 1000;